stages:
- Initialization
- Integration Tests
- Build Docs
- Deploy


## Build Image Templates

.python-template:
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  image: python:3.7-alpine
  cache:
    key: python-${CI_COMMIT_REF_SLUG}
    policy: pull
    paths:
    - .cache/pip
    - venv/

.node-template:
  image: node:11.3-alpine
  cache:
    key: node-${CI_COMMIT_REF_SLUG}
    paths:
    - node_modules/


## Jobs

pip requirements:
  stage: Initialization
  extends: .python-template
  cache:
    policy: pull-push
  script:
  - python -V
  - pip -V
  - pip install -r requirements.txt

npm install:
  stage: Initialization
  extends: .node-template
  cache:
    policy: pull-push
  script:
  - echo node $(node -v)
  - echo npm v$(npm -v)
  - npm install markdownlint-cli

markdownlint:
  stage: Integration Tests
  extends: .node-template
  script:
  - ./node_modules/.bin/markdownlint docs
  except:
    refs:
    - master

mkdocs build:
  stage: Build Docs
  extends: .python-template
  script:
  - mkdocs build
  artifacts:
    name: site
    expire_in: 1 day
    paths:
    - site/

aws s3 sync:
  stage: Deploy
  extends: .python-template
  script:
  - aws s3 sync ./site s3://$S3_BUCKET --delete
  only:
  - master
